//
//  Candy_PickerViewController.m
//  Candy Picker
//
//  Created by Thomas Belote on 2/14/10.
//  Copyright Thomas Belote 2010. All rights reserved.
//

#import "Candy_PickerViewController.h"

#include <stdlib.h>

@implementation Candy_PickerViewController

@synthesize dark;
@synthesize milk;
@synthesize white;
@synthesize nuts;
@synthesize sugar;
@synthesize sugarfree;
@synthesize peanuts;
@synthesize kosher;
@synthesize results;
@synthesize reload;
@synthesize candyChoices;
@synthesize managedObjectContext;

- (IBAction) pressedButtonReload: (id) sender {
	Candy *c;
	NSString *r = @"";
	for (int i = 0 ; i < 12; i++) {
		c = [candyChoices objectAtIndex: (arc4random() % [candyChoices count])];
		r = [r stringByAppendingString:c.name];
		r = [r stringByAppendingString:@"\n"];
	}
	results.text = r;
}


// The designated initializer. Override to perform setup that is required before the view is loaded.
- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil {
    if (self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil]) {
    }
    return self;
}

/*
// Implement loadView to create a view hierarchy programmatically, without using a nib.
- (void)loadView {
}
*/



// Implement viewDidLoad to do additional setup after loading the view, typically from a nib.
- (void)viewDidLoad {
    [super viewDidLoad];
	scrollView.contentSize = CGSizeMake(320,700);
	
	// Custom initialization
	//Candy *milkChocolateButter = [Candy ]
	candyChoices = [[NSMutableArray alloc] init];
	Candy *c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Chocolate Butter - Chocolate buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Chocolate Butter - Chocolate buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Buttercream - Vanilla buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Buttercream - Vanilla buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Cashew Brittle - Hard toffee with cashews and shredded coconut"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Butterscotch Square - Firm brown sugar"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Almond Square - Roasted almonds and caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Bordeaux (tm) - Brown sugar buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Bordeaux (tm) - Brown sugar buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Pecan Buds - Pecans  and vanilla caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Walnut - English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Walnut - English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Almonds - Roasted almonds"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Almonds - Roasted almonds"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: YES]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Peanuts - Roasted peanuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Raspberry Truffle - Rich raspberry chocolate"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Almond Buds - Roasted almonds and caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: YES]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"P-Nut Crunch (tm) - Crunchy peanut butter center"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: NO]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Scotch Kiss - Marshmallow and caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Marzipan - Honey almond paste"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Ginger - Glaced ginger"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"California BrittleÆ - Hard toffee with almonds"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark ButterchewÆ - Vanilla brown sugar caramel with dark chocolate coating"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Chocolate Chip Truffle - Rich chocolate buttercream with chocolate chips"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Maple Walnut - Maple buttercream with English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: NO]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"ScotchmallowÆ - Honey marshmallow and caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Light Chocolate Truffle - Rich chocolate buttercream with ground nutmeats on top"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Mocha - Coffee milk chocolate buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Cocoanut - Cocoanut buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: YES]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Polar Bear PawÆ - Peanuts and vanilla caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Lemon Truffle - Rich lemon chiffon buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark [NSNumber numberWithBool: NO]ugat - Honey [NSNumber numberWithBool: NO]ugat"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Chocolate Truffle - Rich chocolate buttercream with ground nutmeats on top"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Caramel - Caramel with almonds"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Rum [NSNumber numberWithBool: NO]ugat - English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Orange Cream - Orange buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Strawberry Cream - Strawberry buttercream with strawberries"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Raspberry Cream - Raspberry buttercream with raspberries"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Vanilla Nut Cream - Vanilla buttercream with English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Chelsea - Chocolate buttercream with roasted pecans"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: YES]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Divinity - Whipped egg whites"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Walnut Square - Caramel with English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Butterchew - Vanilla"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: YES]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Peanut [NSNumber numberWithBool: NO]ugat - Chewy peanut [NSNumber numberWithBool: NO]ugat"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Pattie - Vanilla caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Pattie - Chocolate vanilla caramel"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"See's Apple Pie TruffleÆ - Rich buttercream with Granny Smith apples and cinnamon"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Vanilla Nut Caramel - Vanilla caramel and pecans"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Key Lime Truffle - Rich buttercream with Key Lime"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Pineapple Truffle - Rich buttercream with pineapple"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"CafÈ au Lait Truffle - Rich coffee buttercream"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Blueberry Truffle - Rich buttercream with blueberries"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Apricot Delight - Apricot buttercream with chopped apricot and toasted coconut"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: YES]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Divinity Puff - Whipped egg whites"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Butterscotch Chew - Vanilla"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Almond Truffle - Dark chocolate buttercream with ground almonds"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Kona Mocha - Coffee"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: YES]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"California Crunch - Crunchy Peanut Butter center w/ ground Englsih Walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: YES]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Peanut Butter Patties - Smooth peanut butter center"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark California BrittleÆ - Hard toffee with almonds covered in dark chocolate"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: YES]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Peanuts - Roasted"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: YES]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Milk Molasses Chips - Molasses honeycomb crisp"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: NO]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Molasses Chips - Molasses honeycomb crisp"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Walnut Roll - Vanilla center with English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: NO]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Mayfair (tm) - Buttercream with cherries and English walnuts"];
	[candyChoices addObject: c];
	c = [NSEntityDescription insertNewObjectForEntityForName:@"Candy" inManagedObjectContext:managedObjectContext];
	[c setKosher: [NSNumber numberWithBool: NO]];
	[c setMilk: [NSNumber numberWithBool: NO]];
	[c setSugarfree: [NSNumber numberWithBool: NO]];
	[c setDark: [NSNumber numberWithBool: YES]];
	[c setSugar: [NSNumber numberWithBool: YES]];
	[c setNuts: [NSNumber numberWithBool: YES]];
	[c setPeanuts: [NSNumber numberWithBool: NO]];
	[c setVegetarian: [NSNumber numberWithBool: YES]];
	[c setWhite: [NSNumber numberWithBool: NO]];
	[c setFavorite: [NSNumber numberWithBool: NO]];
	[c setName: @"Dark Cocoanut Cream - Buttercream with Angel flake coconut"];
	[candyChoices addObject: c]; 
}


/*
// Override to allow orientations other than the default portrait orientation.
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
    // Return YES for supported orientations
    return (interfaceOrientation == UIInterfaceOrientationPortrait);
}
*/

- (void)didReceiveMemoryWarning {
	// Releases the view if it doesn't have a superview.
    [super didReceiveMemoryWarning];
	
	// Release any cached data, images, etc that aren't in use.
}

- (void)viewDidUnload {
	// Release any retained subviews of the main view.
	// e.g. self.myOutlet = nil;
}


- (void)dealloc {
	[dark release];
	[milk release];
	[white release];
	[nuts release];
	[sugar release];
	[sugarfree release];
	[peanuts release];
	[kosher release];
	[results release];
	[reload release];
	[candyChoices release];
	[managedObjectContext release];
    [super dealloc];
}

@end
